import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Book,
  Briefcase,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  CreditCard,
  Dumbbell,
  Flag,
  GraduationCap,
  Heart,
  Home,
  Inbox,
  LayoutDashboard,
  ListChecks,
  Loader2,
  Lock,
  Menu,
  Music,
  Plane,
  Plus,
  Search,
  Settings,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Tag,
  Trash2,
  User,
  X,
  DollarSign,
  Timer,
  Focus,
  Bell,
  Palette,
  Download,
  Upload,
  Database,
  Keyboard,
  RotateCcw,
  Play,
  Pause,
  Square,
  Archive,
  Copy,
  Pencil,
  Repeat,
  LogOut,
  Moon,
  MoreHorizontal,
  CheckCircle2,
  CircleDot,
  ExternalLink,
} from 'lucide-react'
import type { LucideIcon, LucideProps } from 'lucide-react'
import type { ComponentType } from 'react'

const iconMap: Record<string, LucideIcon> = {
  alertTriangle: AlertTriangle,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  archive: Archive,
  book: Book,
  briefcase: Briefcase,
  calendar: Calendar,
  calendarClock: CalendarClock,
  calendarClock2: CalendarClock,
  calendarDays: CalendarDays,
  calendarPlus: CalendarPlus,
  camera: Camera,
  check: Check,
  checkCheck: CheckCheck,
  checkCircle2: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circle: Circle,
  circleDot: CircleDot,
  clock: Clock,
  copy: Copy,
  creditCard: CreditCard,
  database: Database,
  dollarSign: DollarSign,
  download: Download,
  dumbbell: Dumbbell,
  externalLink: ExternalLink,
  flag: Flag,
  focus: Focus,
  graduationCap: GraduationCap,
  heart: Heart,
  home: Home,
  inbox: Inbox,
  keyboard: Keyboard,
  layoutDashboard: LayoutDashboard,
  listChecks: ListChecks,
  loader2: Loader2,
  lock: Lock,
  logOut: LogOut,
  menu: Menu,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  music: Music,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  plane: Plane,
  play: Play,
  plus: Plus,
  repeat: Repeat,
  rotateCcw: RotateCcw,
  search: Search,
  settings: Settings,
  shoppingCart: ShoppingCart,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  sun: Sun,
  tag: Tag,
  timer: Timer,
  trash2: Trash2,
  upload: Upload,
  user: User,
  x: X,
  bell: Bell,
}

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp: ComponentType<LucideProps> | undefined = iconMap[name]
  if (!Cmp) return null
  return <Cmp {...props} />
}

export { iconMap }
